- hosts:
    - parzival.pagina-dh.de
    - default
  gather_facts: False
  vars_files:
    - vars/main.yml
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
    - setup: # aka gather_facts
    - include_vars:
        file: vars/vm.yml
      when: inventory_hostname_short == "default"
    - include_vars:
        file: vars/staging.yml
      when: ansible_fqdn == "parzival.pagina-dh.de"
  roles:
    - williamyeh.reset-locale
    - geerlingguy.firewall
    - geerlingguy.security
    - geerlingguy.postfix
    - geerlingguy.java
    - geerlingguy.nodejs
    - geerlingguy.git
    - geerlingguy.nginx
    - geerlingguy.certbot
    - pagina.tustep
    - pagina.web-project
  tasks:
    - name: Set root mail alias
      lineinfile:
        path: "/etc/aliases"
        line: "root  gregor.middell@pagina.gmbh"
      notify: update aliases

    - name: Install Pythons passlib for htpasswd support.
      apt:
        pkg: python-passlib

    - name: Setup HTTP authentication.
      htpasswd:
        path: "/etc/nginx/htpasswd"
        name: "{{ htpasswd_user }}"
        password: "{{ htpasswd_password }}"
        owner: root
        group: www-data
        mode: 0640

    - name: Install Cisco-VPN client and CIFS client
      apt:
        pkg: "{{ item }}"
      with_items:
        - "vpnc"
        - "cifs-utils"

    - name: Configure VPN to Bern University
      template:
        src: "{{ item.name }}.j2"
        dest: "/etc/vpnc/{{ item.name }}"
        owner: "root"
        group: "root"
        mode: "{{ item.mode }}"
      with_items:
        - name: "unibe.ch.conf"
          mode: "0400"
        - name: "unibe.ch-script"
          mode: "0500"
        - name: "unibe.ch-smb-credentials"
          mode: "0400"

    - name: Create Bern University mount point
      file:
        path: "{{ parzival_smb_mount_path }}"
        state: directory

    - name: Configure systemd services
      template:
        src: "{{ item }}.j2"
        dest: "/etc/systemd/system/{{item}}"
        mode: 0644
      with_items:
        - "vpnc-unibe-ch.service"
        - "srv-bern.mount"
      notify: restart unibe-ch services

    - name: Start and enable VPN
      systemd:
        name: "vpnc-unibe-ch.service"
        enabled: yes
        state: started

    - name: Start and enable /srv/bern mount
      systemd:
        name: "srv-bern.mount"
        enabled: yes
        state: started

    - name: Schedule periodic checks of the Bern University mount
      cron:
        minute: "*/5"
        name: "srv-bern-mount-check"
        job: >
          systemctl -q is-failed srv-bern.mount && systemctl start srv-bern.mount
  handlers:
    - name: update aliases
      command: newaliases

    - name: restart unibe-ch services
      systemd:
        name: "{{ item }}"
        state: restarted
      with_items:
        - "vpnc-unibe-ch.service"